version: "3.3"
services:
  mt5:
    build:
      context: .
      dockerfile: mt5/Dockerfile
    ports:
      - 5678:5678
      - 8080:8080


  # dashboard:
  #   build:
  #     context: .
  #     dockerfile: dashboard/Dockerfile
  #   ports:
  #     - 8501:8501
  #   volumes:
  #   - ./dashboard/dashboard:/code
  #   depends_on:
  #   - redis
  #   - mt5