services:
  mt5:
    image: asc686f61/fx-mt5:test
    build:
      context: .
      dockerfile: mt5/Dockerfile
      network: host
    ports:
      - "8080:8080"
      - "5928:8080"
      - "8000:8000"
    # volumes:
    #   - ./docker/mt5/:/root/.wine/drive_c/fx
    environment:
      - ACCOUNT=
      - PASSWORD=
      - SERVER=
    deploy:
      replicas: 1
